deptry/cli.py
Allows user to run `deptry --version`
=> Added functionality to display current version

README.md, deptry/import_parser.py, deptry/obsolete_dependencies_finder.py, docs/docs/index.md, pyproject.toml
removed some badges from readme and docs, improved logging, modified project description
=> removed some badges from readme and docs, modified project description

deptry/config.py, deptry/dependency_getter.py, deptry/import_parser.py, deptry/issue_finders/misplaced_dev.py, deptry/issue_finders/transitive.py, deptry/module.py, deptry/python_file_finder.py, deptry/utils.py, docs/docs/pyproject-toml.md
=> added more docstrings

README.md, deptry/dependency.py, docs/docs/index.md, docs/docs/usage.md, docs/mkdocs.yml
=> fixed some typos and added warning to documentation

.github/workflows/on-merge-to-main.yml, .github/workflows/on-pull-request.yml, .github/workflows/on-release-main.yml, deptry/module.py, poetry.lock, pyproject.toml, tests/data/example_project/pyproject.toml, tests/test_obsolete_dependencies_finder.py, tests/test_transitive_dependencies_finder.py, tox.ini
=> added support for python 3.11

.github/workflows/on-merge-to-main.yml, .github/workflows/on-pull-request.yml, .github/workflows/on-release-main.yml, deptry/module.py, poetry.lock, pyproject.toml, tests/data/example_project/pyproject.toml, tests/test_obsolete_dependencies_finder.py, tests/test_transitive_dependencies_finder.py, tox.ini
=> Revert "added support for python 3.11"

poetry.lock, pyproject.toml, tests/data/example_project/pyproject.toml, tests/test_obsolete_dependencies_finder.py, tests/test_transitive_dependencies_finder.py
Simplify the environment, so it also works with Python 3.11.
=> Simplified env

deptry/cli.py, deptry/config.py, deptry/core.py, docs/docs/usage.md, tests/test_cli.py
=> Add option --extend-exclude

deptry/cli.py, deptry/cli_defaults.py, deptry/config.py, docs/docs/pyproject-toml.md, docs/docs/usage.md, pyproject.toml, tests/test_cli.py, tests/test_config.py
=> Added comma-separated CLI arguments, added unit tests for configuration

.github/actions/run-checks/action.yml, Makefile, README.md, codecov.yaml, docs/docs/index.md, poetry.lock, pyproject.toml
=> Added codecov

codecov.yaml
=> Added check to fail CI if codecov drops

README.md, docs/docs/index.md
=> Added a warning to not install deptry globally, but within virtual environment

deptry/cli.py, docs/docs/usage.md
=> updated cli docstring and docs

codecov.yaml, tests/test_import_parser.py
=> fixed unit test name

poetry.lock, pyproject.toml
=> fixed python version

deptry/cli.py, deptry/core.py, deptry/result_logger.py, tests/test_core.py, tests/test_result_logger.py
=> added a summary line to the logging

deptry/cli.py
=> changed DIRECTORY argument to ROOT

README.md
=> URL to logo in README instead of relative, so it also works on pypi

.gitignore, deptry/cli.py, deptry/cli_defaults.py, deptry/core.py, deptry/json_writer.py, docs/docs/usage.md, pyproject.toml, tests/test_cli.py, tests/test_json_writer.py
=> Added option to write output to json

deptry/cli.py, deptry/compat.py, deptry/core.py, deptry/dependency.py, deptry/dependency_getter/requirements_txt.py, deptry/dependency_specification_detector.py, deptry/issue_finders/misplaced_dev.py, deptry/issue_finders/transitive.py, deptry/json_writer.py, deptry/module.py, deptry/result_logger.py, deptry/utils.py, poetry.lock, pyproject.toml, tests/test_dependency.py, tox.ini
Resolves #10.
Improve typing to make mypy pass, and activate mypy on the CI.
=> Improve typing to make mypy pass and activate mypy on CI

.github/workflows/validate-codecov-config.yml
Companion PR to https://github.com/fpgmaas/deptry/pull/143.
This PR intends to validate Codecov configuration whenever it is changed, to make sure that it is always valid.
Tested by :
- adding https://github.com/fpgmaas/deptry/pull/144/commits/6a663264b72981db2f19eba32ef98b10e25e0169 that led to [this failing build](https://github.com/fpgmaas/deptry/actions/runs/3160913464/jobs/5145906842)
- adding https://github.com/fpgmaas/deptry/pull/144/commits/1d412136fc889608682b2d9a0912fda49 …
=> ci: validate codecov config on updates

pyproject.toml
Add more package metadata to make the package more discoverable in PyPI, and add myself as a maintainer. The author is already automatically included in the `maintainers`, so there's no need to duplicate it.
=> chore: add more package metadata

pyproject.toml, tests/test_cli.py, tests/test_core.py, tests/test_dependency.py, tests/test_import_parser.py, tests/test_module.py, tests/test_notebook_import_extractor.py, tests/test_pyproject_toml_dependency_getter.py, tests/test_python_file_finder.py, tests/test_requirements_txt_dependency_getter.py, tests/test_result_logger.py, tests/test_transitive_dependencies_finder.py, tox.ini
Run `flake8` on tests to run the same checks as we run on the code and prevent mistakes. Also updating `mypy` configuration so that it runs on scripts.
=> Run flake8 on tests

tests/issue_finders/test_misplaced_dev.py
Add basic tests for `misplaced_dev`, to ease refactoring in https://github.com/fpgmaas/deptry/pull/154.
=> test(issue_finders): add basic test for `misplaced_dev`

docs/docs/usage.md
=> fixed the docs for pre-commit hooks

.github/workflows/main.yml, .github/workflows/on-release-main.yml, pyproject.toml
=> py311 instead of py311 dev, and remove classifier from pyproject.toml

.pre-commit-config.yaml, pyproject.toml
=> Added ruff

docs/docs/faq.md, docs/docs/index.md, docs/docs/pyproject-toml.md, docs/docs/usage.md, docs/mkdocs.yml
Improve the documentation by:
- adding a dark mode and updating the colours (choose cyan as a primary colour and deep orange as an accent colour based on `deptry` logo's colours)
- adding footer icons and fixing the edit URL, that currently doesn't work
- adding type on some code blocks, to correctly highlight them, and fixing a few typos
=> Improve documentation

mkdocs.yml
=> docs: fix PyPI URL

README.md, docs/index.md
=> Fixed build badge

poetry.lock, pyproject.toml
=> downgraded chardet

pyproject.toml, tests/cli/test_cli.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_requirements_txt.py, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/imports/test_extract.py, tests/issues_finder/test_misplaced_dev.py, tests/issues_finder/test_missing.py, tests/issues_finder/test_obsolete.py, tests/issues_finder/test_transitive.py, tests/test_config.py, tests/test_core.py, tests/test_dependency.py, tests/test_dependency_specification_detector.py, tests/test_json_writer.py, tests/test_module.py, tests/test_python_file_finder.py, tests/test_result_logger.py, tests/test_utils.py
Updates `mypy` configuration so that it also runs on tests.
While this is less critical than running it on the library itself, it still ensures that we pass the correct arguments to the different methods we call in the tests (for instance, it spotted issues like passing lists instead of sets, or passing strings instead of paths, etc.).
=> Run `mypy` on tests

deptry/cli.py
Bunch of improvements over the cli command learned from reading https://click.palletsprojects.com/en/8.1.x/options/#callbacks-and-eager-options
=> Improve cli command

deptry/core.py, deptry/dependency_specification_detector.py, deptry/exceptions.py, deptry/utils.py, tests/test_core.py, tests/test_dependency_specification_detector.py
https://github.com/fpgmaas/deptry/pull/280 reports the following new issue: https://github.com/guilatrova/tryceratops/blob/main/docs/violations/TC003.md.
This PR creates dedicated exceptions to respect this new rule.
=> refactor: create dedicated exceptions

.github/workflows/main.yml, tox.ini
-   [ ] ~If there is a related issue, make sure it is linked to this PR.~
-   [ ] ~If you've fixed a bug or added code that should be tested, add tests!~
-   [ ] ~Documentation in `docs` is updated~
Since we not only support Linux but also macOS and Windows, let's run tests on those OSes.
As is, the CI is failing, because both some parts of the code and some tests do not account for Windows.
This proves that it would be useful to add all OSes we support to the CI.
https://github.com/fpgmaas/deptry/pull/343 will fix the issues to make sure that the CI passes.
=> ci: run tests on macOS and Windows

deptry/dependency.py, deptry/dependency_getter/pep_621.py, deptry/dependency_getter/poetry.py, deptry/dependency_getter/requirements_txt.py, tests/unit/issues_finder/test_misplaced_dev.py, tests/unit/issues_finder/test_missing.py, tests/unit/issues_finder/test_obsolete.py, tests/unit/test_dependency.py, tests/unit/test_module.py
Preliminary refactoring to ease the implementation of https://github.com/fpgmaas/deptry/issues/349. It adds the definition file into `Dependency` class, to make it possible to retrieve the file that defined the specification. This will mostly be useful when reporting the error.
=> feat(dependency): enrich with definition file

deptry/core.py, deptry/issues_finder/base.py, deptry/issues_finder/misplaced_dev.py, deptry/issues_finder/missing.py, deptry/issues_finder/obsolete.py, deptry/issues_finder/transitive.py, deptry/reporters/base.py, deptry/reporters/json.py, deptry/reporters/text.py, deptry/violation.py, deptry/violations/__init__.py, deptry/violations/base.py, deptry/violations/misplaced_dev.py, deptry/violations/missing.py, deptry/violations/obsolete.py, deptry/violations/transitive.py, tests/unit/issues_finder/test_misplaced_dev.py, tests/unit/issues_finder/test_missing.py, tests/unit/issues_finder/test_obsolete.py, tests/unit/issues_finder/test_transitive.py, tests/unit/reporters/test_json_reporter.py, tests/unit/reporters/test_text_reporter.py, tests/unit/test_core.py
Preliminary refactoring to ease the implementation of https://github.com/fpgmaas/deptry/issues/349. It implements the concept of violations to hold information related to all found violations. Later on, the location of the module will be added, so we can add it in the text/JSON report.
=> refactor: introduce violations

README.md, docs/index.md
I think that with the improved output formatting by @mkniewallner it would be good to show a small example of the output in the README and in the homepage of the docs, so new users know what they can expect from the tool.
=> Added usage example to README and index of docs

deptry/imports/extract.py
=> fix terminal output when only a single file is scanned

deptry/core.py, deptry/dependency.py, deptry/dependency_getter/base.py, deptry/dependency_getter/requirements_txt.py, deptry/dependency_specification_detector.py, deptry/exceptions.py, deptry/imports/extract.py, deptry/imports/extractors/base.py, deptry/imports/extractors/notebook_import_extractor.py, deptry/imports/extractors/python_import_extractor.py, deptry/issues_finder/misplaced_dev.py, deptry/issues_finder/missing.py, deptry/issues_finder/obsolete.py, deptry/issues_finder/transitive.py, deptry/reporters/json.py, deptry/utils.py, pyproject.toml, tests/functional/cli/test_cli.py, tests/unit/dependency_getter/test_pdm.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/dependency_getter/test_poetry.py, tests/unit/dependency_getter/test_requirements_txt.py, tests/unit/imports/test_extract.py, tests/unit/reporters/test_json_reporter.py, tests/unit/test_config.py, tests/unit/test_dependency_specification_detector.py, tests/unit/test_python_file_finder.py, tests/utils.py
Enable a few more Ruff rules that make sense to have in the codebase:
- [flake8-logging-format](https://beta.ruff.rs/docs/rules/#flake8-logging-format-g)
- [flake8-pytest-style](https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt)
- [flake8-use-pathlib](https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth)
- [flake8-blind-except](https://beta.ruff.rs/docs/rules/#flake8-blind-except-ble)
- [pep8-naming](https://beta.ruff.rs/docs/rules/#pep8-naming-n)
=> chore: add more Ruff rules

CHANGELOG.md
Processed the feedback from https://github.com/fpgmaas/deptry/issues/427. 
It does feel a bit strange to not have a 'deprecation' section while we are deprecating arguments, but the deprecation of these arguments is the consequence of adding some new features. I could not really find a better way to reflect it as it is reflected now.
=> Added release 0.12.0 to changelog

.github/workflows/main.yml
Python 3.12 has [entered beta state](https://peps.python.org/pep-0693/#schedule), so it could be nice to start running tests against it.
=> chore: run tests against Python 3.12

poetry.lock, pyproject.toml, renovate.json5
Enable automerge of PRs created by Renovate that update patch versions, or typing dependencies. This should reduce the time spent in terms of maintenance.
=> chore: setup automerge on Renovate

.github/workflows/main.yml, tox.ini
- Add Python 3.12 which is now available as a github action: https://github.com/actions/python-versions/releases
- Add Python 3.12 tox environment.
=> Add Python 3.12 to the CI and tox.

pyproject.toml
Ref: https://python-poetry.org/docs/pyproject/#urls
This will add a link to the changelog from PyPI.
=> chore(packaging): add link to changelog in metadata

README.md, docs/usage.md
=> Small fix in the docs

CHANGELOG.md
=> Release notes for 0.14.0

tests/utils.py
Find the full path to the wheel file and use that to install within the funtional unit tests. Fixes https://github.com/fpgmaas/deptry/issues/616
=> fix unit tests

CHANGELOG.md
=> docs(changelog): add 0.16.1 release notes

renovate.json5
Hint Renovate on Ruff dependency in `Cargo.toml`, to get updates whenever a new version is published. Tested over https://github.com/mkniewallner/mkv-playground/pull/3/files.
Also removing `pep440-python-dependency` since we don't use it anymore (it was previously used to handle additional dependencies in `.pre-commit-config.yaml`).
=> chore(renovate): hint Renovate on Ruff in `Cargo.toml`

renovate.json5
`config:base` has been deprecated and replaced by `config:recommended` (https://docs.renovatebot.com/presets-config/#configrecommended).
Found by running `npx -p renovate@37.330.0 renovate-config-validator --strict`.
=> chore(renovate): use `config:recommended`

.github/actions/setup-env/action.yml, renovate.json5
Use [PDM action](https://github.com/pdm-project/setup-pdm) to bootstrap virtual environment. The action has builtin support for cache, so this should save a few seconds as we reuse existing installations. Also specifying a specific version of PDM for better reproducibility.
=> ci: use PDM action

rust-toolchain.toml
Announcement: https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html
=> chore(deps): bump `rust` to 1.78

rust-toolchain.toml
Announcement: https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html
=> chore(deps): bump `rust` to 1.79

Cargo.lock, Cargo.toml, src/imports/ipynb.rs, src/imports/py.rs, src/imports/shared.rs, src/visitor.rs
Bump Ruff parser to 0.4.9. There are a few breaking changes handled in separate commits.
=> chore: use 0.4.9 for Ruff parser

Cargo.lock, Cargo.toml
=> chore(deps): use Ruff parser 0.5.0

CHANGELOG.md
=> docs(changelog): add 0.16.2 release notes

.github/workflows/main.yml
Avoid duplication on tests by using a matrix for the OS.
=> ci: avoid duplication on tests

.github/workflows/main.yml
Avoids canceling other jobs if tests fail for one specific platform.
=> ci: do not fail fast on tests

CHANGELOG.md
Add changelog for a proposed `0.17.0` release.
=> release 0.17.0

rust-toolchain.toml
https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html
=> chore(deps): bump `rust` to 1.80

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/validate-codecov-config.yml, .github/workflows/validate-renovate-config.yml
`ubuntu-24.04` is available: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
=> ci: use `ubuntu-24.04`

mkdocs.yml
This was previously only available for insiders, but it's now publicly available: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=prefers#automatic-light-dark-mode.
=> docs: add auto `prefers-color-scheme`

.github/workflows/release.yml, Cargo.lock, Cargo.toml
`generate-import-lib` is needed, per https://pyo3.rs/v0.22.2/features.html?highlight=generate#generate-import-lib.
=> ci: publish wheels for Windows aarch64

Cargo.toml, pyproject.toml, renovate.json5
A few tweaks on linters and Cargo
=> chore: few tweaks on linters and Cargo

.github/workflows/main.yml, mkdocs.yml
Use stricter validation options for `mkdocs`, following the recommendations in https://www.mkdocs.org/user-guide/configuration/#validation. This could prevent some mistakes in the documentation.
=> docs: use stricter validation options

.github/workflows/main.yml, .github/workflows/release.yml
macOS 15 is now available in beta: https://github.com/actions/runner-images/issues/10686.
=> ci: use `macos-15`

tests/functional/conftest.py
uv now provides its own build command through [uv build](https://docs.astral.sh/uv/guides/publish/#building-your-package).
=> test(functional): build wheel using `uv build`

CHANGELOG.md
=> docs(changelog): add 0.21.1 release notes

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/validate-codecov-config.yml, .github/workflows/validate-renovate-config.yml, .pre-commit-config.yaml
Add https://github.com/woodruffw/zizmor-pre-commit to detect and prevent vulnerabilities in GH Actions workflows.
=> chore: add `zizmor-pre-commit` to limit GH Actions vulnerabilities

src/file_utils.rs, src/imports/ipynb.rs, src/imports/py.rs, src/lib.rs, src/python_file_finder.rs, src/visitor.rs
Fixing some issues reported with `cargo clippy --all-targets --all-features -- -W clippy::pedantic -D warnings`.
=> chore(clippy): fix some issues reported with `clippy::pedantic`

Cargo.toml, rust-toolchain.toml, src/imports/shared.rs, src/python_file_finder.rs, src/visitor.rs
https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html
=> chore: bump rust to 1.85

CHANGELOG.md
- [] If there is a related issue, make sure it is linked to this PR.
- [] If you've fixed a bug or added code that should be tested, add tests!
- [] If you've added or modified a feature, documentation in `docs` is updated
Noticed and fixed a missing link in the CHANGELOG.md. No impact for users.
=> Fix missing hyperlink

Cargo.toml, rust-toolchain.toml, src/file_utils.rs, src/imports/ipynb.rs, src/imports/py.rs, src/python_file_finder.rs, src/visitor.rs
Changelog: https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/.
=> chore: bump rust to 1.89
