deptry/import_parser.py, tests/test_import_parser.py
=> fixed issue with import statement with no module, e.g. from . import foo

deptry/cli.py, deptry/core.py, deptry/dependency.py, deptry/dependency_getter.py, deptry/issue_finders/misplaced_dev.py, deptry/issue_finders/missing.py, deptry/issue_finders/obsolete.py, deptry/issue_finders/transitive.py, deptry/module.py, pyproject.toml, tests/test_dependency.py, tests/test_dependency_getter.py, tests/test_obsolete_dependencies_finder.py
If a dependency is not installed, and thus no metadata is found, it will now by default get one top-level module name, which is lowercase and with '-' replaced with '_'. So e.g. `importlib-metadata` will by default get `importlib_metadata` as a top-level module.
If this happens, a warning is displayed in the console to inform the user.
=> Improved handling of conditional and obsolete dependencies

deptry/import_parser.py, tests/test_import_parser.py
=> Solved bug with relative imports being marked as missing

deptry/cli.py, deptry/cli_defaults.py, deptry/import_parser.py, docs/docs/pyproject-toml.md, docs/docs/usage.md, tests/test_import_parser.py
- ignore setuptools from imports, since it is usually installed by default.
- added setup.py to the list of default ignores
=> Setuptools

deptry/dependency_specification_detector.py, tests/test_dependency_specification_detector.py
=> fixed an issue with requirements.txt not being found if not in root dir

codecov.yaml, deptry/core.py, deptry/issue_finders/misplaced_dev.py, tests/test_missing_dependencies_finder.py
=> solved an issue where missing dev dependencies were added to the list as None

deptry/import_parser.py, poetry.lock, pyproject.toml, tests/test_import_parser.py
=> detect file encoding with chardet before parsing the .py file

deptry/import_parser.py, tests/test_import_parser.py
=> changed parsing logic; only try to get encoding if initial parsing fails

deptry/import_parser.py, poetry.lock, pyproject.toml, tests/test_import_parser.py
=> added a unit test for logging encoding issues

deptry/dependency_getter/requirements_txt.py, poetry.lock, pyproject.toml, tests/test_requirements_txt_dependency_getter.py
=> added parsing of egg=... in urls for requirements.txt

deptry/dependency.py, tests/test_dependency.py
=> Added a method to extract top level module names from RECORD

deptry/utils.py, poetry.lock, pyproject.toml, tests/test_utils.py
Replace the library used for parsing `pyproject.toml` by [tomli](https://pypi.org/project/tomli/) on Python < 3.11 and [tomllib](https://docs.python.org/3.11/library/tomllib.html) on Python 3.11+.
`tomli` provides the same API as `tomllib`, which will be [included in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html), so it is more future-proof.
Besides, `toml` is [mostly unmaintained](https://github.com/uiri/toml/commits/master).
=> Switch to `tomli`/`tomllib` for parsing TOML

docs/docs/pyproject-toml.md
`extend_exclude` is missing from the `pyproject.toml` configuration documentation.
Also took the occasion to add the expected type for the lists elements.
=> docs(pyproject): add missing `extend_exclude`

codecov.yaml
`status` key in Codecov configuration is misplaced, since it it is currently under `ignore` instead of `coverage`, as shown [in the documentation](https://docs.codecov.com/docs/commit-status).
=> chore(codecov): fix misplaced `status`

poetry.lock, pyproject.toml
[mock](https://pypi.org/project/mock/) module doesn't seem to be used in the codebase.
=> build(deps): remove unneeded `mock` module

.pre-commit-config.yaml, deptry/dependency_getter/pyproject_toml.py, deptry/dependency_getter/requirements_txt.py, deptry/import_parser.py, deptry/issue_finders/misplaced_dev.py, deptry/module.py
Add some helpful `flake8` plugins to the codebase:
- [flake8-bugbear](https://pypi.org/project/flake8-bugbear/) to find bugs/design flaws
- [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/) to simplify list/set/dict comprehensions
- [flake8-simplify](https://pypi.org/project/flake8-simplify/) to simplify over-complex code
Update code to comply with the new checks.
Raw list of suggestions:
- `flake8-bugbear`:
```python
deptry/module.py:51:68: B006 Do not use mutable data structures for …
```
=> Add some helpful `flake8` plugins

pyproject.toml
See https://github.com/psf/black/issues/438
If we ever want to exclude anything, we should add an exclude argument in `pre-commit-config.yaml`.
=> removed `exclude` from black configuration since it's not used by pre-commit

codecov.yaml
Checking Codecov shows that the configuration is correctly invalid, as shown by https://app.codecov.io/gh/fpgmaas/deptry/commit/a701a5ae931d5d3f0dc59abc797b871b39009879.
Using the method described in https://docs.codecov.com/docs/codecov-yaml#validate-your-repository-yaml to validate the configuration:
```bash
$ curl -sSL --fail-with-body --data-binary @codecov.yaml https://codecov.io/validate
Error at ['coverage', 'status', 'project', 'default', 'threshold']: 
field 'threshold' …
```
=> Fix `threshold` field in Codecov configuration and un-ignore modules

deptry/cli.py, deptry/core.py, deptry/dependency.py, deptry/dependency_getter/requirements_txt.py, deptry/dependency_specification_detector.py, deptry/issue_finders/misplaced_dev.py, deptry/issue_finders/missing.py, deptry/issue_finders/obsolete.py, deptry/module.py, deptry/result_logger.py, pyproject.toml, tests/test_cli.py, tests/test_dependency_specification_detector.py, tests/test_import_parser.py, tests/test_json_writer.py, tests/test_pyproject_toml_dependency_getter.py, tests/test_python_file_finder.py, tests/test_requirements_txt_dependency_getter.py
Update `black` configuration:
- `target-version` should be set to the minimum Python we support
- `fast`, while faster, [doesn't check that the AST after reformatting is valid](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting), meaning that there's no guarantee that the code still works; removing it should be safer
- `preview` enables [future style updates](https://black.readthedocs.io/en/stable/the_black_code_style/futu …
=> Update `black` configuration

Makefile, poetry.lock
https://github.com/fpgmaas/deptry/actions/runs/3164427038/jobs/5152707386 shows that `poetry.lock` is not consistent with what is defined in `pyproject.toml`:
```bash
Run poetry install --no-interaction
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```
This PR refreshes it, and adds a step in `check` Make task to ensure at the CI level that the …
=> Re-lock Poetry dependencies

deptry/cli.py, deptry/compat.py, deptry/dependency.py, deptry/dependency_getter/pyproject_toml.py, deptry/dependency_getter/requirements_txt.py, deptry/import_parser.py, deptry/issue_finders/transitive.py, deptry/json_writer.py, deptry/module.py, deptry/notebook_import_extractor.py, deptry/utils.py, pyproject.toml
Enable `strict` mode for `mypy`, which enables the following flags, according to `--strict` documentation:
```console
$ poetry run mypy --help | grep -A 8 "\--strict "
--strict                  Strict mode; enables the following flags: --warn-
unused-configs, --disallow-any-generics,
--disallow-subclassing-any, --disallow-untyped-
calls, --disallow-untyped-defs, --disallow-
incomplete-defs, --check-untyped-defs, --disallow-
untyped-decorators, --no-implicit-optional, …
```
=> Enable strict mode for `mypy` + other error codes

Makefile, poetry.lock, pyproject.toml
Coverage is currently set up to run statement coverage rather than branch one. [Branch coverage](https://coverage.readthedocs.io/en/6.5.0/branch.html#branch) is more granular, since it ensures that every possible branch of a function is measured.
This PR switches to branch coverage, and set a few more options:
- [source](https://coverage.readthedocs.io/en/6.5.0/config.html#run-source) specifies the files to measure (without that, tests themselves are currently measures in the …
=> Improve coverage report

.pre-commit-hooks.yaml, docs/docs/usage.md
Second try at this based on previous reviews -- do we still want to try to provide a hooks file?
@wpdonders
Reference: https://github.com/fpgmaas/deptry/pull/124
=> [feature] add hooks for using with pre-commit

.github/actions/setup-poetry-env/action.yml
https://github.com/fpgmaas/deptry/actions/runs/3320886881/jobs/5487809759#step:4:20 highlights that we are currently running tox under Python 3.10 regardless of the Python version sent as an input, because we share the cache key regardless of the version.
=> ci: add Python version to cache key

.github/actions/check-docs/action.yml, .github/actions/deploy-docs/action.yml, .github/actions/setup-poetry-env/action.yml, .github/workflows/on-release-main.yml
https://github.com/fpgmaas/deptry/actions/runs/3373976926 outputs a few deprecations warnings that this PR handles by:
- removing `set-output` usage
- bumping `actions/*` dependencies:
- `actions/cache` changelog: [v3.0.0](https://github.com/actions/cache/releases/tag/v3.0.0)
- `actions/checkout` changelog: [v3.0.0](https://github.com/actions/checkout/releases/tag/v3.0.0)
- `actions/setup-python` changelogs: [v3.0.0](https://github.com/actions/setup-python/releases/tag/v3.0.0) / …
=> Handle CI deprecation warnings

.pre-commit-config.yaml, deptry/cli_defaults.py, deptry/dependency_getter/requirements_txt.py, deptry/notebook_import_extractor.py, deptry/python_file_finder.py, tests/cli/test_cli.py, tests/test_json_writer.py
Add https://github.com/asottile/pyupgrade/ to our pre-commit hooks.
The library rewrites code to newer syntax of Python versions, which will prove useful the day we drop support for Python 3.7.
A nice feature of `pyupgrade` is also https://github.com/asottile/pyupgrade/#python2-and-old-python3x-blocks, which will rewrite a conditional import whenever the Python version in the condition is not supported anymore.
=> Add `pyupgrade` to pre-commit

deptry/core.py, deptry/import_parser.py, deptry/module.py, tests/issues_finder/test_misplaced_dev.py, tests/issues_finder/test_missing.py, tests/issues_finder/test_obsolete.py, tests/issues_finder/test_transitive.py, tests/test_import_parser.py, tests/test_module.py
Resolves #171.
Update `_remove_local_file_imports` method so that it correctly considers local imports for modules in the root directory of a project.
=> fix(import_parser): remove obsolete duplicated local import detection

deptry/core.py, deptry/dependency_getter/pdm.py, deptry/dependency_getter/pep_621.py, deptry/dependency_specification_detector.py, docs/docs/index.md, docs/docs/usage.md, tests/cli/test_cli_pep_621.py, tests/data/pep_621_project/README.md, tests/data/pep_621_project/pyproject.toml, tests/data/pep_621_project/src/main.py, tests/data/pep_621_project/src/notebook.ipynb, tests/data/project_with_pdm/pyproject.toml, tests/dependency_getter/test_pep_621.py, tests/test_dependency_specification_detector.py
Resolves #109.
Add support for PEP 621 dependency specification. This will ensure that modern package managers that follow PEP 621 are supported.
The implementation makes the assumption that optional dependencies under `[project.optional-dependencies]` are all non-development ones. In a follow up PR, https://github.com/fpgmaas/deptry/issues/162#issuecomment-1290501638 could be an interesting option to have to define groups that should be considered development dependencies groups. …
=> Add support for PEP 621

.pre-commit-config.yaml, renovate.json5
I don't think it's important to check for outdated dependencies every day, so to prevent getting notifications every day I propose to run on Saturday only.
Also added a renovate config check to the pre-commit hook.
=> Run renovate on saturdays and add renovate config check to pre-commit hook

deptry/cli_defaults.py, deptry/result_logger.py, docs/pyproject-toml.md, docs/usage.md, poetry.lock
=> add .direnv to default exclude argument

deptry/cli.py, deptry/config.py, deptry/core.py, deptry/dependency.py, deptry/dependency_getter/base.py, deptry/dependency_getter/pdm.py, deptry/dependency_getter/pep_621.py, deptry/dependency_getter/poetry.py, deptry/dependency_getter/requirements_txt.py, deptry/dependency_specification_detector.py, deptry/imports/extract.py, deptry/issues_finder/base.py, deptry/issues_finder/misplaced_dev.py, deptry/issues_finder/missing.py, deptry/issues_finder/obsolete.py, deptry/issues_finder/transitive.py, deptry/json_writer.py, deptry/module.py, deptry/python_file_finder.py, deptry/result_logger.py, deptry/utils.py, tests/test_python_file_finder.py
Since [PEP 585](https://peps.python.org/pep-0585/) implemented in Python 3.9, generic types can be used for type annotations in replacement of their counterparts in `typing` module.
`deptry` supports `Python >= 3.7`, but thanks to [`from __future__ import annotations`](https://peps.python.org/pep-0585/#implementation), it's possible to use those generic types on 3.7+.
=> refactor: use generic types instead of `typing`

.pre-commit-config.yaml, deptry/compat.py, deptry/core.py, pyproject.toml, tests/imports/test_extract.py, tests/test_dependency_specification_detector.py
`ruff` [can replace `isort`](https://github.com/charliermarsh/ruff#how-does-ruffs-import-sorting-compare-to-isort) for dependency sorting. Since we already have `ruff` running in `pre-commit`, I thought it could be a good idea to fully replace `isort` and rely on `ruff` for import sorting.
The PR also enables a few more rules, to better match what we have in `flake8`. There are still rules that we use through `flake8` plugins that are not yet implemented in `ruff`, so it might be …
=> Use `ruff` for import sorting and add more rules

.github/workflows/validate-renovate-config.yml, .pre-commit-config.yaml, renovate.json5
Most of the contributors won't ever update `renovate` configuration, yet the `pre-commit` hook takes quite some time to install locally (at least for me).
So instead of running it through `pre-commit`, this PR moves the workflow to a dedicated GitHub Actions workflow, similarly to the one we have for `codecov` configuration.
The PR also updates the schedule for lock file maintenance, so it runs on Saturday, same as the other updates, instead of Monday (which also allows validating …
=> chore: move `renovate-config-validator` to GH Actions

README.md, docs/index.md
See https://github.com/badges/shields/issues/8671
=> changed badge url

.github/workflows/main.yml, renovate.json5, tox.ini
`tox` workflow is currently broken because we don't pin a specific version of `tox-gh-actions`, and a new major version was released yesterday (https://github.com/ymyzk/tox-gh-actions/releases/tag/v3.0.0).
This made us automatically pick up `tox>=4`, which removed `whitelist_externals` option in favour of `allowlist_externals` (https://github.com/tox-dev/tox/releases/tag/4.0.0rc4).
So the PR updates the parameter used, and updates the installation of `tox-gh-actions` to pin a …
=> ci: fix `tox` workflow

deptry/core.py
Local modules retrieval is currently done multiple times, as it's done in a for loop. This PR makes sure that it's only done once, greatly reducing the run time on big projects.
=> perf(core): only load local modules once

deptry/python_file_finder.py
Noticed a bunch of performance improvements that could be made to the method that retrieves Python files.
Tested over a few projects with some ignored patterns, and it reduced the duration spent in the method by ~25%.
=> perf(finder): more efficient Python files retrieval

deptry/cli.py, deptry/core.py, deptry/utils.py, tests/cli/test_cli.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_requirements_txt.py, tests/cli/test_cli_src_directory.py, tests/data/project_with_src_directory/pyproject.toml, tests/data/project_with_src_directory/src/project_with_src_directory/bar.py, tests/data/project_with_src_directory/src/project_with_src_directory/foo.py, tests/data/project_with_src_directory/src/project_with_src_directory/notebook.ipynb, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/imports/test_extract.py, tests/test_config.py, tests/test_dependency_specification_detector.py, tests/test_json_writer.py, tests/test_python_file_finder.py, tests/utils.py
`deptry` allows passing the root directory as a positional argument, which gives some flexibility to projects that use different kind of structures.
This is for instance useful for projects that use an `src` directory structure, like [Poetry](https://github.com/python-poetry/poetry/tree/master/src/poetry) or [Hatch](https://github.com/pypa/hatch/tree/master/src/hatch).
Unfortunately, the root directory passed as a command line means that the configuration file will be read from …
=> Separate `pyproject.toml` location from `root` argument

deptry/cli.py, deptry/config.py, deptry/core.py, deptry/dependency_getter/base.py, deptry/dependency_getter/pdm.py, deptry/dependency_getter/pep_621.py, deptry/dependency_getter/poetry.py, deptry/dependency_specification_detector.py, deptry/utils.py, docs/usage.md, tests/cli/test_cli_pyproject_different_directory.py, tests/data/project_with_pyproject_different_directory/a_sub_directory/pyproject.toml, tests/data/project_with_pyproject_different_directory/src/project_with_src_directory/bar.py, tests/data/project_with_pyproject_different_directory/src/project_with_src_directory/foo.py, tests/data/project_with_pyproject_different_directory/src/project_with_src_directory/notebook.ipynb, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/test_config.py, tests/test_dependency_specification_detector.py, tests/test_utils.py
This PR builds upon https://github.com/fpgmaas/deptry/pull/244, to allow explicitly specifying the location of `pyproject.toml`, which can be useful for projects passing a root directory different than `.` where `pyproject.toml` is stored in the specified root directory.
=> Expose and handle `--config` argument

deptry/cli.py, deptry/core.py, deptry/python_file_finder.py, docs/usage.md, poetry.lock, pyproject.toml, tests/cli/test_cli.py, tests/cli/test_cli_gitignore.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/data/project_with_gitignore/.gitignore, tests/data/project_with_gitignore/pyproject.toml, tests/data/project_with_gitignore/src/bar.py, tests/data/project_with_gitignore/src/foo.py, tests/data/project_with_gitignore/src/foobar.py, tests/data/project_with_gitignore/src/notebook.ipynb, tests/test_python_file_finder.py
Resolves #200.
This PR implements the changes suggested in the linked issue with the help of [pathspec](https://pypi.org/project/pathspec/), with a slight modification: it doesn't empty the default `exclude` list. Since not all projects use `git`, I figured that it might be better to keep this default list.
=> Exclude files from `.gitignore`

tests/cli/test_cli.py, tests/cli/test_cli_gitignore.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_pyproject_different_directory.py, tests/cli/test_cli_requirements_txt.py, tests/cli/test_cli_src_directory.py, tests/utils.py
It is rather painful to write CLI tests against the console output in case of errors.
This PR updates CLI tests that check for errors so that they use JSON output, making the assertions way more bearable, while ensuring that all 4 types of issues are checked.
=> test(cli): use JSON output to simplify tests on errors

mkdocs.yml, poetry.lock, pyproject.toml
Changelog: https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.0
Upgrade guide: https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x
Also removing `mkdocstrings` since it's not currently used.
=> build(deps): bump `mkdocs-material` to `9.0.0`

renovate.json5
If we don't specify a timeframe, Renovate could create multiple PRs during the day once we merge the first PRs it creates, which can be noisy.
According to
https://docs.renovatebot.com/configuration-options/#schedule, it doesn't support exact time (probably because Renovate runs are not exactly predictable), so setting "before 3am" and "before 5am" should give it enough time to make PRs, while making it almost sure that we won't get new PRs during the day after the first ones …
=> chore(renovate): tweak schedule

deptry/imports/extract.py, tests/imports/test_extract.py
Resolves #261.
Don't filter out `setuptools` in the import extractor, in order to let users do it explicitly through `ignore_*` settings if really needed.
=> feat(extract): don't filter out `setuptools`

.pre-commit-config.yaml, pyproject.toml, tox.ini
`ruff` now supports most `flake8-simplify` rules (https://github.com/charliermarsh/ruff/issues/998). Since the last ones will most likely be implemented sooner than later, and all other rules we use for `flake8` are implemented, it might be time to fully rely on `ruff` and drop `flake8`.
Also taking the occasion to add [flake8-builtins](https://github.com/charliermarsh/ruff#flake8-builtins-a) rules.
=> chore: drop `flake8` to only use `ruff`

.github/workflows/validate-renovate-config.yml, renovate.json5
Add the recently released https://docs.renovatebot.com/presets-regexManagers/#regexmanagersgithubactionsversions regex and use it for bumping the version of `node`. Current regex doesn't work. I thought it was implemented in this repository, but it was only in my own [Renovate configuration repository](https://github.com/mkniewallner/renovate-config/blob/13ef46c725c5f3872d31ec533cdc86d3c96ed6c2/default.json5#L41-L48) :see_no_evil:
=> chore(renovate): use GitHub Actions regex

.pre-commit-config.yaml, deptry/dependency.py, deptry/dependency_specification_detector.py, deptry/module.py, pyproject.toml, tests/imports/test_extract.py
Use `ruff` to replace `pyupgrade` ([almost all rules](https://github.com/charliermarsh/ruff/issues/827) are implemented) and `pygrep-hooks` ([the only rule](https://github.com/charliermarsh/ruff#pygrep-hooks-pgh) we use is implemented, the other are either nice to have, or should not cause any harm).
Also enable more rules that would be nice to have in the codebase, but feel free to tell me if you disagree with some:
- [flake8-2020](https://github.com/charliermarsh/ruff#flake8-2020 …
=> chore: use more `ruff` rules and replace `pyupgrade` and `pygrep-hooks` usages

deptry/__init__.py, deptry/compat.py, deptry/imports/extractors/__init__.py, deptry/stdlibs.py, pyproject.toml, tests/cli/test_cli.py, tests/cli/test_cli_gitignore.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_pyproject_different_directory.py, tests/cli/test_cli_requirements_txt.py, tests/cli/test_cli_src_directory.py, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/issues_finder/test_misplaced_dev.py, tests/issues_finder/test_obsolete.py, tests/test_config.py, tests/test_dependency_specification_detector.py, tests/test_json_writer.py, tests/test_utils.py
In order to be able to use generics for typing (`dict`, `list`, `set`, etc.) on Python < 3.9, `from __future__ import annotations` needs to be added. As it can be easy to forget to add it when needed, I thought we could use [`required-imports`](https://github.com/charliermarsh/ruff#required-imports) from Ruff to automatically add it everywhere.
=> chore(ruff): add `from __future__ import annotations` as required import

.pre-commit-config.yaml, deptry/config.py, deptry/core.py, deptry/dependency_getter/base.py, deptry/dependency_getter/pdm.py, deptry/dependency_specification_detector.py, deptry/imports/extract.py, deptry/imports/extractors/base.py, deptry/imports/extractors/notebook_import_extractor.py, deptry/issues_finder/base.py, deptry/issues_finder/misplaced_dev.py, deptry/issues_finder/missing.py, deptry/issues_finder/obsolete.py, deptry/issues_finder/transitive.py, deptry/module.py, deptry/utils.py, pyproject.toml, tests/cli/test_cli.py, tests/cli/test_cli_gitignore.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_pyproject_different_directory.py, tests/cli/test_cli_requirements_txt.py, tests/cli/test_cli_src_directory.py, tests/imports/test_extract.py, tests/issues_finder/test_transitive.py, tests/test_config.py, tests/test_json_writer.py, tests/test_result_logger.py
Enable rules from https://github.com/snok/flake8-type-checking to detect imports that are only necessary for type checking and need to be moved under `if TYPE_CHECKING` condition.
Combined with `from __future__ import annotations` to not interpret type annotations at runtime, It has the following benefits:
- reducing the import time overhead
- limiting the possibility of ending up with circular imports
=> chore(ruff): enable `flake8-type-checking`

renovate.json5
The schedule doesn't always give enough time for Renovate to be triggered, so increasing a bit the max time on the schedule should do the trick.
=> chore(renovate): set schedule up to 5am

deptry/dependency_specification_detector.py
fixes the typo in #293 
As a security measure, I ran pre-commit and tests with 100% success rate 💪🏼
=> fix(dependency-detector): replace 'PDM' with 'poetry' (typo)

renovate.json5
This allows retrieving release notes from
https://github.com/charliermarsh/ruff/releases, to have actual release notes instead of not having anything.
=> chore(renovate): set custom changelog URL for `ruff-pre-commit`

poetry.lock, pyproject.toml, renovate.json5
Renovate v35 updated [`rangeStrategy`](https://docs.renovatebot.com/configuration-options/#rangestrategy) so that it defaults to `update-lockfile`. This means that it will make pull request to update each dependency separately in the lock file if the update respect the range defined.
Since we already have regular lock files updates that already take care of that, we can only keep this single PR.
The PR also updates dev dependencies to use specific versions instead of ranges. As …
=> chore(renovate) set `rangeStrategy` to `replace` and pin dev dependencies

pyproject.toml
I noticed that a test fails in https://github.com/fpgmaas/deptry/pull/333 due to a coverage delta being too negative. It is induced by `if TYPE_CHECKING:` blocks, which should be ok.
This PR suggests some lines of code that may be excluded from coverage, as they generally are not ment to. It's a subset of what's suggested to be a good default by the [covdefaults](https://pypi.org/project/covdefaults/) library.
=> exclude some lines from coverage

deptry/core.py, tests/cli/test_cli_src_directory.py, tests/data/project_with_src_directory/pyproject.toml, tests/data/project_with_src_directory/src/foobar.py, tests/data/project_with_src_directory/src/project_with_src_directory/bar.py, tests/test_core.py
Since [PEP 420](https://peps.python.org/pep-0420/), it is not required for Python modules to have an `__init__.py` to be considered a Python module.
We also today only consider directories and not Python files.
This PR handles this case by relaxing `_get_local_modules` method to account for 2 things:
- Directories that don't contain any `__init__.py`, by checking for any Python file
- Files that are Python files (end up with `.py` extension)
Tests have been updated to reflect what …
=> feat(core): handle local modules without `__init__.py`

deptry/cli.py, deptry/core.py, deptry/dependency.py, deptry/dependency_getter/base.py, deptry/dependency_getter/pdm.py, deptry/dependency_getter/pep_621.py, deptry/dependency_getter/poetry.py, deptry/dependency_getter/requirements_txt.py, docs/usage.md, tests/cli/test_cli_arg_types.py, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/test_core.py, tests/test_dependency.py
Adding a pre-configured map between package names and module names, so not installed modules don't produce errors when a package name doesn't auto-convert to the module name. E.g. package name `foo-python` is translated to module `foo_python`, but it's actually called `foo`.
Fixes https://github.com/fpgmaas/deptry/issues/332
```toml
[tool.deptry.package_module_name_map]
foo-python = [
"foo",
]
```
Before adding tests & docs, let's see if this is an acceptable problem & solution …
=> A way to pre-configure a map of package names to module names

deptry/imports/extractors/notebook_import_extractor.py, deptry/imports/extractors/python_import_extractor.py, deptry/python_file_finder.py, tests/cli/test_cli.py, tests/cli/test_cli_gitignore.py, tests/cli/test_cli_pdm.py, tests/cli/test_cli_pep_621.py, tests/cli/test_cli_pyproject_different_directory.py, tests/cli/test_cli_requirements_txt.py, tests/cli/test_cli_src_directory.py, tests/imports/test_extract.py, tests/test_core.py, tests/test_python_file_finder.py, tests/utils.py
-   [ ] ~If there is a related issue, make sure it is linked to this PR.~
-   [ ] ~Documentation in `docs` is updated~
This PR enables https://github.com/fpgmaas/deptry/pull/342 by fixing a few issues spotted when trying to add the CI on Windows.
https://github.com/mkniewallner/deptry/pull/23 shows that Windows jobs are green when including the fixes from this PR.
=> fix: account for Windows in code and tests

deptry/dependency.py, docs/usage.md, tests/dependency_getter/test_pdm.py, tests/dependency_getter/test_pep_621.py, tests/dependency_getter/test_poetry.py, tests/dependency_getter/test_requirements_txt.py, tests/test_dependency.py
It should have been split across multiple PRs, but I'm trying it like this anyway:
* The translated package name is now only added to the recognized top level modules if no mapping or metadata is found.
* If a metadata file is found, but it's empty, no alternative methods of finding top level module names will be tried. Previously no distinction was made between not found and found but empty.
* optimized the code a bit to reduce the up to three `metadata.distribution(name)` calls …
=> Only use translated pkg name as fallback + some optimization

.github/actions/setup-poetry-env/action.yml, .github/workflows/main.yml, pyproject.toml, tox.ini
https://github.com/fpgmaas/deptry/pull/364 fails because Poetry is installed in the same environment as dependencies by tox, following the changes in https://github.com/fpgmaas/deptry/pull/342.
I originally intended to keep using `allowlist_externals` to maintain a separation between Poetry and the environment, but I couldn't make it work on Windows.
As it seems using `tox` doesn't bring that much values on the CI, and actually adds a bit of complexity, I figured we could remove …
=> chore: remove `tox` from CI

docs/issues-detection.md, docs/usage.md
Add error codes to issue titles. Also reword a bit transitive dependencies example, and remove a leftover from https://github.com/fpgmaas/deptry/pull/357/commits/90b58016247500b0724f64bf535e100655662055.
=> docs: add error codes + some cleanup

deptry/cli.py, deptry/core.py, deptry/imports/location.py, deptry/reporters/text.py, deptry/violations/misplaced_dev.py, deptry/violations/missing.py, deptry/violations/obsolete.py, deptry/violations/transitive.py, docs/usage.md, poetry.lock, pyproject.toml, tests/functional/cli/test_cli.py, tests/functional/cli/test_cli_gitignore.py, tests/functional/cli/test_cli_pdm.py, tests/functional/cli/test_cli_pep_621.py, tests/functional/cli/test_cli_pyproject_different_directory.py, tests/functional/cli/test_cli_requirements_txt.py, tests/functional/cli/test_cli_src_directory.py, tests/unit/reporters/test_json_reporter.py, tests/unit/reporters/test_text_reporter.py, tests/unit/test_core.py, tests/utils.py
Follow up on https://github.com/fpgmaas/deptry/pull/357 to add colours to the terminal output, similarly to other tools like `flake8`, `ruff` or `mypy`.
A `--no-ansi` option is also added on the CLI to be able to disable this behaviour, for terminals that do not support ANSI characters, or if users want to opt-out from this.
On Windows, ANSI characters do not work out-of-the-box, so we leverage https://github.com/tartley/colorama to be able to display colours.
=> feat: add colours to text output

deptry/issues_finder/misplaced_dev.py, tests/unit/issues_finder/test_misplaced_dev.py
=> Fix issue with DEP004 being raised incorrectly

deptry/python_file_finder.py, tests/data/project_with_src_directory/.gitignore, tests/data/project_with_src_directory/src/this_file_is_gitignored.py
`.gitignore` is currently looked for based on the root directory passed as a CLI argument. This means that developers using a `src` directory and invoking `deptry` with `deptry src` won't benefit from gitignore being loaded.
I don't think that there are a lot of use cases where `.gitignore` would be located in a different directory that the one `deptry` is launched from, so this PR updates the behaviour so that `.gitignore` is always loaded based on where `deptry` is invoked.
If …
=> fix(python_file_finder): load gitignore from where CLI is invoked

deptry/dependency_getter/poetry.py, tests/data/project_with_poetry/poetry.toml, tests/data/project_with_poetry/pyproject.toml, tests/data/project_with_poetry/src/main.py, tests/data/project_with_poetry/src/notebook.ipynb, tests/functional/cli/test_cli_poetry.py, tests/unit/dependency_getter/test_poetry.py
Resolves #391.
Update Poetry dependencies parsing logic to consider dependencies from all groups as development dependencies.
=> feat(poetry): consider all groups for dev dependencies

deptry/imports/extractors/notebook_import_extractor.py, deptry/imports/extractors/python_import_extractor.py
Since https://github.com/python/cpython/pull/97594, `ast.parse` can now raise `SyntaxError` while it would previously raise `ValueError`. This change was backported to 3.11.4, [breaking our current test suite](https://github.com/fpgmaas/deptry/actions/runs/5298012283/jobs/9590133734) on Windows for Python 3.11.
Also removing [`UnicodeDecodeError`](https://docs.python.org/3/library/exceptions.html#UnicodeDecodeError), because it's a subclass of …
=> fix(imports): handle `SyntaxError`

deptry/__main__.py, tests/functional/cli/test_cli.py, tests/functional/cli/test_cli_gitignore.py, tests/functional/cli/test_cli_multiple_source_directories.py, tests/functional/cli/test_cli_pdm.py, tests/functional/cli/test_cli_pep_621.py, tests/functional/cli/test_cli_poetry.py, tests/functional/cli/test_cli_pyproject_different_directory.py, tests/functional/cli/test_cli_requirements_txt.py, tests/functional/cli/test_cli_src_directory.py, tests/functional/conftest.py, tests/functional/types.py, tests/unit/reporters/test_text.py, tests/unit/violations/dep002_unused/test_finder.py, tests/utils.py
Functional tests currently run in the same virtual environment as the one running the tests, meaning that dependencies dependencies installations of each functional test are actually shared with the main virtual environment.
This causes issues at multiple levels:
- Functional tests outputs are less predictable
- Unit tests outputs, as well as CI workflows (see https://github.com/fpgmaas/deptry/pull/439#issuecomment-1627094658), are affected by dependencies installations from …
=> test(functional): use isolated virtual environments

.pre-commit-config.yaml, renovate.json5
[black](https://github.com/psf/black) releases [wheels compiled with `mypyc`](https://black.readthedocs.io/en/stable/contributing/release_process.html#mypyc-wheels), which are faster, but by using `pre-commit`, we are forced to build wheels, and they are not compiled with `mypyc`. [A mirror](https://github.com/psf/black-pre-commit-mirror) was [recently created](https://github.com/psf/black/issues/3405#issuecomment-1600079594) by one of `black`'s maintainers, which uses a similar …
=> chore(pre-commit): use mirror for `black` to use `mypyc` wheels

.pre-commit-config.yaml, pyproject.toml, renovate.json5, tests/unit/deprecate/test_ignore_flags.py
Replace Black with [Ruff format](https://astral.sh/blog/the-ruff-formatter). Black preview style is not fully supported yet (https://github.com/astral-sh/ruff/issues/6935), but given the small size of our codebase, this should not be too much of a problem, and full support for it is likely to be fully implemented rather quickly.
=> chore: replace `black` with `ruff format`

deptry/dependency_getter/requirements_txt.py, tests/unit/dependency_getter/test_requirements_txt.py
Resolves #539.
-   [ ] [not applicable] ~Documentation in `docs` is updated~
This strictens URL guessing when parsing `requirements.txt` format files by using `urllib.parse.urlparse`. At some point it would be nice to leverage parsing of dependencies to https://pypi.org/project/packaging/, although the library does not support legacy URL formats that AFAIK are still supported by `pip`, despite not being recommended anymore. I have a draft PR for this in https://github.com/mkniewallner/deptry/pull/29 that I should someday …
=> fix(dependency_getter): stricten URL guessing

deptry/config.py, deptry/exceptions.py, tests/unit/test_config.py
Detect invalid configuration options set in `[tool.deptry]` section of `pyproject.toml` based on the list of existing arguments in the CLI. This will facilitate the removal of deprecated options, since currently, invalid options do not throw any runtime error, so if we end up removing options we have deprecated, the now gone options would just be ignored instead of throwing an error.
=> feat(config): detect invalid `pyproject.toml` options

pyproject.toml
Currently, the badge at the top of the README shows:
[![Supported Python versions](https://img.shields.io/pypi/pyversions/deptry)](https://pypi.org/project/deptry/)
I believe this can be resolved by adding the correct classifiers.
=> Add python version classifiers

Cargo.toml
Per https://nnethercote.github.io/perf-book/build-configuration.html, there are a few optimisations we could apply to the artifacts we build when releasing.
Testing locally on macOS ARM, this lead to:
- ~5% runtime performance improvements when running `deptry` on a repository with ~7k files (from ~1.02s to ~970ms)
- ~20% reduction on the binary size (from 2.0M to 1.6M)
The tradeoff being that we will have longer compilation times, but since this should only impact the "release" …
=> chore(cargo): aim for faster runtime on `release` profile

.github/workflows/release.yml, pyproject.toml
* Added PyPy as a build target for macOS, Linux and Windows
* Wheels are listed before publishing them to PyPI
```
.
├── pyproject-toml
│   └── pyproject.toml
├── wheels-linux-aarch64-3.11
│   └── deptry-0.0.1-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
├── wheels-linux-aarch64-pypy3.10
│   └── deptry-0.0.1-pp310-pypy310_pp73-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
├── wheels-linux-x86_64-3.11
│   └── …
```
=> Build PyPy wheels

src/imports.rs, tests/unit/imports/test_extract.py
Resolves #618.
It looks like using the logger during parallel processing blocks the process. So this PR delegates logging to `get_imports_from_py_files`, after the parallel processing.
Unit tests and local testing with a directory that contains a file with a syntax error, and a file that is correct. Without the change, for both, the process hangs.
=> fix(imports): handle errors after processing AST

pyproject.toml
Resolves #623.
We've lost license classifier when switching from Poetry to PDM. Poetry [sets that automatically](https://python-poetry.org/docs/pyproject#classifiers), but PDM does not.
=> chore(packaging): set license classifier

pyproject.toml
Backport of #623 to 1.4.x. Will tag a 0.14.2 right after.
=> [1.4] chore(packaging): set license classifier (#624)

README.md, docs/CNAME, mkdocs.yml, pyproject.toml, python/deptry/cli.py, python/deptry/reporters/text.py, tests/functional/cli/test_cli.py, tests/unit/reporters/test_text.py
I propose we migrate the documentation to `deptry.com`. By changing the repository settings, Github created [this commit](https://github.com/fpgmaas/deptry/commits/gh-pages/). This will be overwritten the next time we deploy the documentation, so we need to add the `CNAME` file to the `docs` directory. In addition, I updated the URL's in various locations in the repo.
=> Move docs to deptry.com

python/deptry/core.py, python/deptry/dependency_getter/base.py, python/deptry/dependency_getter/pdm.py, python/deptry/dependency_getter/pep_621.py, python/deptry/dependency_getter/poetry.py, python/deptry/dependency_getter/requirements_txt.py, tests/data/project_with_pdm/pyproject.toml, tests/functional/cli/test_cli.py, tests/functional/cli/test_cli_pdm.py, tests/unit/test_core.py
Since PDM is based on PEP 621, we should probably also handle the new option added in https://github.com/fpgmaas/deptry/pull/628.
This also fixes the logging by moving the logic to `core`, otherwise we would log dev depencencies twice for PDM (once in `PEP621DependencyGetter` and once in `PDMDependencyGetter`.
=> feat(pdm): handle PEP 621 dev groups

docs/usage.md, pdm.lock, python/deptry/cli.py, python/deptry/core.py, python/deptry/dependency_getter/base.py, python/deptry/dependency_getter/pdm.py, python/deptry/dependency_getter/pep_621.py, python/deptry/dependency_getter/poetry.py, python/deptry/dependency_getter/requirements_txt.py, tests/data/pep_621_project/pyproject.toml, tests/data/project_with_pdm/pyproject.toml, tests/functional/cli/test_cli.py, tests/functional/cli/test_cli_pdm.py, tests/functional/cli/test_cli_pep_621.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/test_core.py
For projects that use PEP 621 without `Poetry` or `PDM`, all dependencies under `[project.dependencies]` and `[project.optional-dependencies]` are extracted as regular dependencies. This PR adds the `--pep621-dev-dependency-groups` argument, so users can specify which groups defined under `[project.optional-dependencies]` should be treated as development dependencies instead.
For example, consider a project with the following `pyproject.toml`:
```
[project]
...
dependencies = [ …
```
=> Allow specifying which groups under [project.optional-dependencies] are considered development dependencies

Cargo.lock, Cargo.toml
Unfortunately Renovate does not yet handle git dependencies for Cargo (see https://github.com/renovatebot/renovate/issues/26531), so we'll have to manually update from time to time, or define a custom regex to handle that.
=> chore(deps): bump Ruff AST parser to 0.3.4

pdm.lock, pyproject.toml
Obsolete since https://github.com/fpgmaas/deptry/pull/606.
Maybe `deptry` should learn to find unneeded typing dependencies as well (half-joking 😄).
=> chore(deps): remove obsolete `types-chardet`

python/deptry/violations/dep003_transitive/violation.py, tests/unit/reporters/test_json.py, tests/unit/reporters/test_text.py
Resolves #643.
We currently show the package name for DEP003, but ignore rules take the Python module name into account for DEP003, not the package name. So this PR updates the report to show the Python module name instead.
We might want to consider switching to the package name for the ignore rule, and show the package name in the report as well, but this would technically be a breaking change for users that already define ignore rules and use the Python module name, so I'd …
=> fix(violations): show module name for DEP003

docs/usage.md, src/visitor.rs, tests/data/some_imports.py, tests/unit/imports/test_extract.py
Resolves #556.
When guarding imports with `TYPE_CHECKING` in combination with `from __future__ import annotations`, they are not evaluated at runtime (https://peps.python.org/pep-0563/). This PR implements that behavior, by completely skipping those imports in the import visitor.
An alternative implementation could be to flag dependencies as "typing only" instead of skipping them. This would allow `deptry` to trigger `DEP001` (missing dependencies).
This would also avoid having …
=> feat(visitor): skip type checking blocks

src/imports/ipynb.rs, tests/data/example_project/src/notebook.ipynb, tests/functional/cli/test_cli_requirements_txt.py, tests/unit/imports/test_extract.py
Resolves #653.
Avoid parsing [magics](https://ipython.readthedocs.io/en/stable/interactive/magics.html) in notebooks, as they are not valid Python but notebook-specifics. Also fixes an issue with continuation characters that comes from the fact that we don't strip `\n` suffixes in notebook source code, which also caused the location reporters to show the wrong line location.
=> fix(imports): remove invalid lines when parsing notebooks

pyproject.toml
Enable https://docs.astral.sh/ruff/rules/implicit-namespace-package/, as this is known to cause some issues with some tools. The [original repository](https://github.com/adamchainz/flake8-no-pep420?tab=readme-ov-file#rationale) provides a bit more information about the rationale.
=> chore(ruff): enable `flake8-no-pep420`

.github/actions/setup-env/action.yml, .github/workflows/main.yml, .github/workflows/release.yml
https://github.com/fpgmaas/deptry/actions/runs/8523309964/job/23345314629 shows that ARM jobs in testing don't actually use ARM (which is not really surprising, since we only use `x86_64` images). For instance, we can see:
```console
Downloading zstandard-0.22.0-cp310-cp310-macosx_10_9_x86_64.whl (920 kB)
```
To test against ARM, we would need to use ARM images (which only exist for macOS on GitHub Actions). I don't believe that using ARM brings that much values for tests, so it's …
=> ci: tweak workflows

docs/usage.md, src/visitor.rs, tests/data/some_imports.py, tests/unit/imports/test_extract.py
Resolves #661.
Implementation in https://github.com/fpgmaas/deptry/pull/652 was a bit too defensive, for invalid reasons. `from __future__ import annotations` is not relevant in the context of `deptry`, as not using it will still allows setting types but in quotes. So we should also skip those imports when a module does not use `from __future__ import annotations`.
=> fix(visitor): skip type checking blocks without future annotations

pyproject.toml, tests/functional/conftest.py
Resolves https://github.com/fpgmaas/deptry/issues/636.
Contrarily to what I though, running tests on multiple workers with `pytest-xdist` will run `pytest_sessionstart` several times:
- once from "master" node, when test suite starts
- X times (where X is the number of workers), when tests start in each worker
This was not obvious because the message we print in `pytest_sessionstart` is not displayed in workers, but this can easily be reproduced with:
```python
import uuid
def pytest_sessionstart() -> None:
with open(str(uuid.uuid4()), "w"):
pass
```
then running:
```shell
pdm run pytest tests/functional -n 2 --dist loadgroup
```
which will end up creating 3 files.
Since in our case we only want to run the hook once, we want to explicitly skip …
=> test(conftest): ensure that `pytest_sessionstart` hook runs once

docs/usage.md
Resolves #673.
Quoting an example to avoid piping command. Also switching to double quotes on some examples using single quotes, for consistency.
=> docs(usage): quote CLI example to not pipe command

Cargo.lock, Cargo.toml, tests/unit/imports/test_extract.py
Bump Ruff parser to 0.4.1. [0.4.0](https://github.com/astral-sh/ruff/releases/tag/v0.4.0) introduced a whole new parser that is described [here](https://astral.sh/blog/ruff-v0.4.0).
=> chore: use 0.4.1 for Ruff parser

Cargo.lock, Cargo.toml, src/imports/shared.rs, src/lib.rs, src/python_file_finder.rs
Bump `pyo3` to 0.21 following [this migration guide](https://pyo3.rs/v0.21.1/migration). Bump of `pyo3-log` is also needed, as the current version does not support `pyo3` 0.21.
=> chore(deps): bump `pyo3` to 0.21.0 and `pyo3-log`

.pre-commit-config.yaml, renovate.json5
I feel dumb for not thinking about this, but the implementation in https://github.com/fpgmaas/deptry/pull/692 does not work as expected, as this will not refresh `Cargo.lock`, as can be seen in https://github.com/fpgmaas/deptry/pull/694 (since Renovate doesn't handle the dependency as a Cargo one). So this PR removes this, but also adds lock files check, which would have prevented the PR updating Ruff from getting merged, as the lock file was inconsistent.
=> chore(pre-commit): check lock files

python/deptry/dependency.py, python/deptry/dependency_getter/pep_621.py, python/deptry/dependency_getter/poetry.py, python/deptry/dependency_getter/requirements_files.py, tests/unit/dependency_getter/test_pdm.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/dependency_getter/test_poetry.py, tests/unit/dependency_getter/test_requirements_txt.py
Noticed that we never use optional/conditional information apart from `Dependency.__str__`. This might be something that could be used in the future, but if we do need it at some point, the code will be in git history, so IMO we might as well remove code if we don't need it.
=> refactor(dependency): remove unused optional/conditional

.github/actions/setup-env/action.yml, tests/functional/conftest.py
Recently our CI/CD pipeline failed during the functional tests on Windows in Github Actions. After adding some more verbose output to the tests, we can see that this is because we encounter errors while buiulding the wheel with maturin, see [here](https://github.com/fpgmaas/deptry/actions/runs/9429723770/job/25976421728). e.g.
```
pdm.termui: error[E0463]: can't find crate for `pyo3`
pdm.termui:  --> src\lib.rs:3:5
pdm.termui:   |
pdm.termui: 3 | use pyo3::prelude::*;
pdm.termui:   |     ^^^^ can't find crate
```
After some testing, this seems to be caused by a problem with the cache. Taking a closer look at the [Swatinem/rust-cache@v2](https://github.com/Swatinem/rust-cache) step, I believe we are using it wrong and it might be superfluous. …
=> Remove rust cache

python/deptry/dependency_getter/builder.py, python/deptry/dependency_getter/pep_621.py, python/deptry/dependency_getter/poetry.py, tests/unit/dependency_getter/test_builder.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/dependency_getter/test_poetry.py
We currently hard access `dependencies` key for both PEP 621 and Poetry projects to retrieve dependencies. Although not common, it could happen that projects use `deptry`, but do not have any production dependencies (for instance when bootstrapping a project from a minimal template, where you don't start with any dependency, but still want to include `deptry` in the CI workflow).
This PR soft accesses dependencies for both PEP 621 and Poetry. As for Poetry, we rely on `dependencies` to determine if a project uses Poetry, the logic is also updated to assume that a project uses by only checking `[tool.poetry]` instead of `[tool.poetry.dependencies]`. This should not be problematic, as `[tool.poetry]` is specific to Poetry, and Poetry only.
=> fix(dependency_getter): avoid error on empty dependencies

.github/workflows/main.yml
Newest macOS runners are faster (most likely because it runs on ARM). Just want to see if it also speeds up PyPy builds to an acceptable level.
=> ci: test against PyPy on macOS

renovate.json5
Disable lock file maintenance for cargo, as per https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio, and spotted in https://github.com/fpgmaas/deptry/pull/768/files, it can end up bumping patch/minor versions of direct dependencies.
Although this can be "ok" as long as tests pass:
- it does not play well with Renovate, for which the source of truth is `Cargo.toml`, so it ends up bumping dependencies that have already been bumped (for instance for case above: https://github.com/fpgmaas/deptry/pull/769)
- I personally prefer to read the changelog for direct dependencies before any upgrade, especially for minor versions
=> chore(renovate): disable lockfile maintenance for cargo

docs/rules-violations.md, python/deptry/core.py, python/deptry/module.py, python/deptry/violations/__init__.py, python/deptry/violations/base.py, python/deptry/violations/dep001_missing/finder.py, python/deptry/violations/dep002_unused/finder.py, python/deptry/violations/dep003_transitive/finder.py, python/deptry/violations/dep004_misplaced_dev/finder.py, python/deptry/violations/dep005_standard_library/finder.py, python/deptry/violations/dep005_standard_library/violation.py, python/deptry/violations/finder.py, scripts/generate_stdlibs.py, tests/data/pep_621_project/pyproject.toml, tests/data/pep_621_project/src/main.py, tests/functional/cli/test_cli_pep_621.py, tests/unit/test_core.py, tests/unit/violations/dep001_missing/test_finder.py, tests/unit/violations/dep002_unused/test_finder.py, tests/unit/violations/dep003_transitive/test_finder.py, tests/unit/violations/dep004_misplaced_dev/test_finder.py, tests/unit/violations/dep005_standard_library/test_finder.py
This PR proposes to fix https://github.com/fpgmaas/deptry/issues/760 by adding a `DEP005` to `deptry` that detects dependencies that are already in the standard library. Running this on [this example project](https://github.com/fpgmaas/deptry-example) results in the following:
```
Scanning 1 file...
pyproject.toml: DEP002 'pathlib' defined as a dependency but not used in the codebase
pyproject.toml: DEP005 'asyncio' is defined as a dependency but it is included in the Python standard library.
pyproject.toml: DEP005 'pathlib' is defined as a dependency but it is included in the Python standard library.
Found 3 dependency issues.
For more information, see the documentation: https://deptry.com/
```
For situations where a package is first avaialble on PyPI and then added to the standard …
=> Add `DEP005` to detect dependencies that are in the standard library

docs/usage.md, src/visitor.rs, tests/data/some_dyn_imports.py, tests/data/some_imports.py, tests/unit/imports/test_extract.py
Commits:
- test: add coverage for dynamic import with importlib
- feat(WIP): attempt to get importlib imports
- test: add test coverage for both importlib formats
- feat: also handle case where importlib.import_module is aliased
- refactor: consolidate proof of concept test into existing test
- refactor(clippy): collapse nested `if let` statements in `Stmt::Expr` match arm
- docs: note which sort of `importlib` import are supported
- Support for imports given as string literals directly to `importlib.import_module` 
#780
=> Support imports using `importlib.import_module`

.github/actions/setup-env/action.yml
The CI has been failing quite a while lately. It seemed quite random, but the jobs that don't fail actually just retrieve cache, so by luck, they are not affected.
Debugging a bit the issue in https://github.com/fpgmaas/deptry/pull/794, spotted that the following error was returned when invoking `cargo` commands:
```console
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.80-x86_64-unknown-linux-gnu' toolchain
```
Explicitly adding `cargo` through `rustup` fixes that.
Also adding `--no-self` to `pdm install` because we already build the project when invoking `maturin develop`, so it's not necessary to do both.
=> ci: install `cargo` before dependencies install

docs/rules-violations.md
The example in the documentation for DEP003: transitive dependencies mentions explicitly adding `certifi` to the dependencies as the solution. 
However (and confusingly) in the toml code example the package `httpcore` is added. 
This PR makes sure the example toml code matches the written instructions by replacing `httpcore` in the example with `certifi`.
=> docs: fix DEP003 example by explicitly adding certifi

.github/workflows/release.yml
Should fix the issue spotted in
https://github.com/fpgmaas/deptry/actions/runs/10292527780/job/28487127720 for now:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
```
Need to see how to best handle this, but in the meantime, let's revert to a working workflow.
=> ci: use `ubuntu-22.04` on `sdist` for now

.github/workflows/release.yml
Same player shoots again (https://github.com/fpgmaas/deptry/pull/800).
=> ci: use `ubuntu-22.04` on `publish` for now

.github/workflows/release.yml
Add ability to manually trigger the release in dry-run mode (skipping upload and doc update steps). This will make it possible to test that we can build the wheels and source distribution properly before releasing, or when we do major changes to how they are built.
Tested in my fork, it works as expected (steps skipped on manual trigger, but not on real releases).
=> ci: add ability to dry-run release

pyproject.toml, tox.ini
With https://github.com/fpgmaas/deptry/pull/713 merged, we now test against Python 3.13. Since tests work as expected, we can add Python 3.13 classifier to hint at it being supported.
=> chore(package): add Python 3.13 classifier

python/deptry/cli.py, tests/functional/cli/test_cli.py
By default, `click` wraps lines at 80 characters. This makes the command descriptions in `help` command hard to read properly IMO:
Per [the documentation](https://click.palletsprojects.com/en/8.1.x/documentation/#preventing-rewrapping), there is a way to change that. Using [shutil.get_terminal_size](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size) should be a sensible choice, as it will first check if the terminal provides the right information, then the OS if not, then fallback to a default `80` value (which is already what we have) if neither do.
On a full-size terminal, with a 1920x1080 screen resolution, this looks like this:
=> feat(cli): set max terminal width based on terminal

rust-toolchain.toml
Announcement: https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html.
=> chore(deps): bump `rust` to 1.81

renovate.json5
uv does not support dependency groups yet, so this rule does not do anything anymore, since there's no `typing` group.
=> chore(renovate): remove obsolete typing deps automerge

.github/workflows/release.yml
We had to go back to `ubuntu-22.04` on https://github.com/fpgmaas/deptry/pull/800 and https://github.com/fpgmaas/deptry/pull/801. The issue was that we did not install a specific Python version, so we defaulted to the default one provided by the image, which ends up being externally managed.
Smoke-testing the release workflow in https://github.com/fpgmaas/deptry/actions/runs/10753197835/job/29822356943 and it now works as expected.
=> ci: use `ubuntu-24.04` again for release

.github/workflows/main.yml, .github/workflows/release.yml
Python 3.13 final is [out](https://blog.python.org/2024/10/python-3130-final-released.html). This updates the CI to use it instead of pre-releases, and defaults jobs to 3.13 instead of 3.12.
=> ci: use Python 3.13 final + default to Python 3.13

python/deptry/dependency_getter/requirements_files.py, tests/functional/utils.py, tests/unit/dependency_getter/test_requirements_txt.py
Extracted from https://github.com/fpgmaas/deptry/pull/881. This makes the extraction of dynamic dependencies from `setuptools` cleaner than having to instantiate `RequirementsTxtDependencyGetter`.
=> refactor(dependency_getter): extract requirements files extraction

docs/usage.md, python/deptry/dependency_getter/pep621/base.py, python/deptry/dependency_getter/pep621/pdm.py, python/deptry/dependency_getter/pep621/uv.py, tests/data/pep_621_project/pyproject.toml, tests/data/pep_621_project/src/main.py, tests/data/project_with_pdm/pyproject.toml, tests/data/project_with_pdm/src/main.py, tests/data/project_with_uv/pyproject.toml, tests/data/project_with_uv/src/main.py, tests/functional/cli/test_cli_pdm.py, tests/functional/cli/test_cli_pep_621.py, tests/functional/cli/test_cli_uv.py, tests/unit/dependency_getter/test_pdm.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/dependency_getter/test_uv.py
Closes #885.
Add support for [PEP 735](https://peps.python.org/pep-0735/) dependency groups. Assuming for now that all groups are developments ones, but we might want to make that configurable, following what is described in the issue. Since the PEP is quite new, and not even implemented in any package manager yet, I'd prefer to leave that aside for now, and see if the need to define some dependency groups as non-dev ones is something we need to add support for at some point.
Note that for now, AFAIK none of the PEP 621-compliant package managers support PEP 735 yet, but the PR still by default assumes that they do. Several reason for that:
- I believe most package managers will eventually support PEP 735
- Users of a package manager that …
=> feat: support PEP 735 dependency groups

rust-toolchain.toml
Announcement: https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html.
=> chore(deps): bump `rust` to 1.82

docs/supported-dependency-managers.md, docs/usage.md, mkdocs.yml
With the recent implementation of PEP 735 dependency groups (and the upcoming `setuptools` dynamic dependencies one), the [dependencies extraction documentation](https://github.com/fpgmaas/deptry/blob/main/docs/usage.md#dependencies-extraction) became even more cluttered that it was.
Having a dedicated documentation that lists supported dependency managers would make things way more readable for users, and makes it possible to provide clear examples that explain how deptry extracts dependencies for each manager.
=> docs: better showcase supported dependency managers

tests/unit/violations/dep003_transitive/test_finder.py
Spotted in https://github.com/fpgmaas/deptry/actions/runs/11560721483/job/32178177873 that those tests depend on packages that deptry itself depends on, which is not great. Explicitly mocking `package` avoids that.
=> test(violations): correctly test DEP003

.github/workflows/main.yml, .github/workflows/release.yml, pyproject.toml, uv.lock
uv now supports [`dependency-groups`](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups), so we can switch to it. Support in Renovate was also recently added (https://docs.renovatebot.com/modules/manager/pep621/#additional-information), so we won't lose dependency updates.
=> chore: use `dependency-groups`

tests/unit/test_cli.py
Extracted from https://github.com/fpgmaas/deptry/pull/861.
=> test(cli): add tests for `display_deptry_version`

tests/fixtures/pep_621_project/pyproject.toml, tests/fixtures/pep_621_project/src/main.py, tests/fixtures/project_with_pdm/pyproject.toml, tests/fixtures/project_with_pdm/src/main.py, tests/fixtures/project_with_uv/pyproject.toml, tests/fixtures/project_with_uv/src/main.py, tests/functional/cli/test_cli_pdm.py, tests/functional/cli/test_cli_pep_621.py, tests/functional/cli/test_cli_uv.py
Did some debugging in https://github.com/fpgmaas/deptry/pull/934 to investigate slowness on Windows PyPy tests, and for some reason running PDM tests take about 10 minutes. Removing dependency over `mkdocs` seems to solve the slowness. Although we don't notice the same slowness, doing the same on other tests for consistency.
=> test(functional): remove dependency over `mkdocs`

pyproject.toml, python/deptry/dependency.py, python/deptry/dependency_getter/pep621/base.py, tests/unit/dependency_getter/test_pdm.py, tests/unit/dependency_getter/test_pep_621.py, tests/unit/dependency_getter/test_uv.py, tests/unit/test_dependency.py, uv.lock
Closes #735.
In https://github.com/fpgmaas/deptry/pull/913, we've changed the way we parse dependencies from requirements by switching to `requirements-parser`. This partly replaces what was done in https://github.com/fpgmaas/deptry/pull/735.
Since the dependency we added itself depends on `packaging`, we can leverage it to parse dependencies defined in PEP 621, without adding a new dependency.
=> feat(pep621): use `packaging`-based PEP 508 parser

python/deptry/dependency_getter/pep621/base.py, tests/fixtures/project_with_setuptools_dynamic_dependencies/pyproject.toml, tests/unit/dependency_getter/test_pep_621.py
Closes #944.
It might not be obvious from [`setuptools` documentation](https://setuptools.pypa.io/en/stable/userguide/pyproject_config.html#dynamic-metadata), but `file` attribute can either be a string or a list of strings.
=> fix(dependency_getter): handle strings for `setuptools` dynamic dependencies

rust-toolchain.toml
Release notes: https://blog.rust-lang.org/2024/11/28/Rust-1.83.0.html.
=> chore(deps): bump Rust to 1.83

.github/workflows/release.yml
Closes https://github.com/fpgmaas/deptry/issues/977.
Publish wheels for `musl` so that users on `alpine` can use the library without building from source.
I was able to test this on `aarch64` with macOS ARM by [running a dry-run release](https://github.com/fpgmaas/deptry/actions/runs/12419884904), then extracting the wheel into a Docker container using `python:alpine`:
```console
$ unzip wheels-linux-aarch64-musllinux_1_1-3.13.zip \
&& docker run --workdir /app --volume .:/app python:3.9-alpine \
sh -c 'pip install deptry-0.0.1-cp39-abi3-musllinux_1_1_aarch64.whl && deptry .'
[...]
Found 70 dependency issues.
For more information, see the documentation: https://deptry.com/
```
I don't have access to an `x64` system right now, but I trust that it …
=> ci: publish `musl` wheels for Linux

.github/workflows/release.yml, CHANGELOG.md
Release notes for 0.21.2.
Pinning `maturin` to a specific version for now as the release pipeline currently [fails](https://github.com/fpgmaas/deptry/actions/runs/12419884904/job/34676219092) for Windows aarch64 on more recent versions.
=> docs(changelog): add 0.21.2 release notes

.github/workflows/main.yml, .github/workflows/release.yml
https://github.blog/changelog/2024-12-19-windows-server-2025-is-now-in-public-preview/
=> ci: use `windows-2025`

.github/workflows/release.yml
Documentation publishing is [broken](https://github.com/fpgmaas/deptry/actions/runs/12422008903/job/34683187227). Reproduced on a dummy repository, where setting up permissions to allow writing contents fixed the issue.
=> ci: set permissions when publishing docs

.github/workflows/release.yml, zizmor.yml
Credentials here are needed to push to `gh-pages` branch.
This will fix https://github.com/fpgmaas/deptry/actions/runs/12422008903/job/34683187227.
=> chore: fix docs publishing

python/deptry/dependency_getter/builder.py, tests/unit/dependency_getter/test_builder.py
Tiny performance improvement. Searching for uv before PDM makes sense IMO, as I believe more projects use uv than PDM now.
=> perf(dependency_getter): search for uv before PDM

rust-toolchain.toml
https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html
=> chore: bump rust to 1.84

.github/workflows/main.yml, .github/workflows/release.yml, zizmor.yml
Use cache for pre-commit and uv everywhere, and test more steps in dry-run mode for release.
=> ci: misc improvements

Cargo.toml, rust-toolchain.toml
https://blog.rust-lang.org/2025/05/15/Rust-1.87.0/
=> chore: bump rust to 1.87

.github/renovate.json5
This is considered [a good practice](https://docs.renovatebot.com/upgrade-best-practices/#extends-helperspingithubactiondigests), and is even [reported by zizmor](https://docs.zizmor.sh/audits/#unpinned-uses).
=> chore(renovate): pin GitHub actions

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/validate-codecov-config.yml, .github/workflows/validate-renovate-config.yml
This will make it easier to track changes, otherwise when pinning major, we only see the digest upgrade (https://github.com/fpgmaas/deptry/pull/1174).
=> ci: pin patch versions for actions

pyproject.toml
Seems like `readme` field is missing, causing the [PyPI page](https://pypi.org/project/deptry/) to display
> The author of this package has not provided a project description
This PR proposes to fix that.
=> add readme to pyproject.toml
